UMMS-Biocore/dolphin-ui

public/js/dolphin/ngstrack_stats.js
Forgot to add this into the daterange section as well
=> added sample t able fix for daterange

scripts/dolphin_wrapper.py
=> 2015 05 06 white space fix

application/views/pipeline/rerun.php, application/views/pipeline/selected.php, public/js/dolphin/pipeline_gen_funcs.js
tabbed a few things and fixed the commonind case sensitive structure as well as the json_parameters commonind structure
=> fixed case sensitive commonind database errors

application/controllers/fastlanecontroller.php, application/models/fastlane.php, application/views/fastlane/footer.php, application/views/fastlane/header.php, application/views/fastlane/index.php, application/views/fastlane/process.php
This should fix the controller error
=> adding files not previously added

application/controllers/plotcontroller.php, application/models/plot.php, application/views/plot/footer.php, application/views/plot/header.php, application/views/plot/index.php, public/js/dolphin/ngs_plots.js
Beginning of the plots section, nothing too pretty as of yet
=> 2015 05 12 plots

application/controllers/fastlanecontroller.php, application/views/fastlane/index.php, application/views/pipeline/rerun.php, application/views/pipeline/selected.php, library/html.class.php, public/ajax/ngsfastlanedb.php, public/js/dolphin/ngsfastlane_database_funcs.js, public/js/dolphin/ngsfastlane_funcs.js
Fixed some glaring fastlane issues and took care of a few small problems elsewhere
=> 2015 05 12 fastlane debug

application/views/fastlane/index.php, library/html.class.php, public/js/dolphin/ngsfastlane_database_funcs.js, public/js/dolphin/ngsfastlane_funcs.js
The only issue that I see arising is a missed character condition for the inputs
=> Fixed some lingering bugs within the fastlane

public/js/dolphin/ngsstatus_funcs.js
You have to love those bloopers
=> fixed select service

public/api/ext, scripts/dolphin_wrapper.py
Since, there can be a delay writing into this table in some cases.
=> Try query runparams in dolphin wrapper till record saved into the table

docs/excelexport.rst, docs/excelimport.rst, docs/index.rst, docs/ngsbrowser.rst
=> 2015 07 28 documentation

db/2015_08_31_wkeylist.sql, public/ajax/kill_pid.php, public/ajax/ngsalterdb.php, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngspost_funcs.js
I haven't tested all the possible test cases but this should fix our issue.  Double check if you have time.
=> wkeylist.sql added, insert script changed

application/views/search/browse.php, application/views/search/details.php, application/views/search/index.php, public/ajax/browse_edit.php, public/ajax/ngsquerydb.php, public/ajax/sessionrequests.php, public/js/dolphin/browse_edit.js, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngsget_funcs.js, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/pipeline_gen_funcs.js
new functionality, might want to test more before integrating.
=> 2015 09 01 removal funcs

application/controllers/tablecreatorcontroller.php, application/models/tablecreator.php, application/views/tablecreator/footer.php, application/views/tablecreator/header.php, application/views/tablecreator/index.php, application/views/tablecreator/table.php, application/views/tablecreator/tablereports.php, db/2015_10_16_ngs_createtables.sql, library/html.class.php, public/ajax/ngsquerydb.php, public/ajax/tablegenerator.php, public/api/funcs.php, public/api/getsamplevals.php, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/pipeline_gen_funcs.js, public/js/dolphin/plots.js, public/js/dolphin/tablecreator_funcs.js
The send to plots from the table page isn't functional, but this should give you an idea on what i'm going for.  don't forget the database update.
=> 2015 10 17 tablecreator

includes/admin/smallboxes.php, includes/dbfuncs.php, includes/smallboxes.php, public/ajax/dashboardquerydb.php, public/js/dolphin/admindashboard.js, public/js/dolphin/dashboard.js
Reverts UMMS-Biocore/dolphin-ui#194
=> Revert "2015 11 02 dashboard rework"

public/js/dolphin/pipeline_gen_funcs.js
checkboxes are added as 0 or 1 to their respective pipeline.
Order for tophat:
RNA-Seq QC, RNA metrics, other metrics, mark duplicates
=> 2015 11 12 pipeline additions

includes/login.php, includes/loginform.php, includes/newuser.php, includes/newuser_verification.php, library/auth.php
I was unable to test the full functionality of the code since docker doesn't seem to want to recognize the LDAP server?  Please give it a test before you merge.  main code change are lines 56 through 72.  If the users account has been created but we don't have their information within our database, it'll fail the login.
=> 2015 11 12 login issue

public/api/funcs.php
=> if start time hasn't been uploadded for a reason. It tries to recover at

application/models/ngsimport.php, config/config.ini, public/api/funcs.php, scripts/dolphin_wrapper.py, unitTesting/api/funcs_unittest.php
fixes include:
minutes into import
check functions
checks multiple files all at once
removal of blank variable checks
email addition to config
altered email sending
Will test on dolphin dev for emails and imports first
=> ngsimports changes

public/ajax/ngsalterdb.php, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngspost_funcs.js, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/ngstrackstatus.js, public/js/dolphin/pipeline_gen_funcs.js, unitTesting/ajax/ngsalterdb_unittest.php
This push should set the status to 5 if it needs to wait before it calls the wrapper.
the ! button in the samples list is also no more, and the check for initial run to send to the pipeline is gone.
=> 2016 02 10 instant submission

application/controllers/searchcontroller.php, application/models/search.php, application/views/search/details.php, application/views/search/footer.php, db/2016_03_08_datafields.sql, library/html.class.php
Test this out and let me know what you think
=> 2016 03 07 details

public/ajax/ngsalterdb.php, public/js/dolphin/ngstrackstatus.js
The only 'error' I cannot fix is if you queue your run and immediately reset it.  The ui will set the run status to 6, but the back end kicks up an error and updates it to run status 3 after the fact.
=> 2016 03 14 error

public/ajax/tablegenerator.php, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/tablecreator_funcs.js, unitTesting/ajax/tablegenerator_unittest.php
There are currently no checks to see if the JSON2 file is present if the JSON file has been created.  TO overide this, simply remove either the JSON file itself or the file name from the database and reload the page.  The system will see that the JSON file is not there and create both files.
JSON2 file is required for the 'send to plots' page.  JSON file is used for DEBrowser.
=> 2016 03 21 plots

application/views/search/footer.php, public/ajax/ngs_stat_funcs.php, public/api/funcs.php, public/js/dolphin/ngsstatus_funcs.js, public/js/dolphin/ngstrackstatus.js
it's not finished but you can test the functionality for now if you'd like
=> 2016 03 18 job reset

includes/dbfuncs.php, public/ajax/tablegenerator.php, public/api/getsamplevals.php, public/js/dolphin/tablecreator_funcs.js
Going to test on dolphin-dev. do not merge.
=> multiple selection box for table creator

application/controllers/fastlanecontroller.php, application/models/ngsimport.php, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngsfastlane_database_funcs.js
also donor can no longer have spaces
=> 2016 03 31 import

application/controllers/fastlanecontroller.php, application/controllers/ngsimportcontroller.php, application/models/ngsimport.php, public/ajax/initialmappingdb.php, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngsfastlane_database_funcs.js, public/js/dolphin/ngsfastlane_funcs.js, public/js/dolphin/ngsget_funcs.js, public/js/dolphin/ngsstatus_funcs.js, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/pipeline_gen_funcs.js, public/js/dolphin/sessionget_funcs.js, public/js/dolphin/tablecreator_funcs.js, unitTesting/ajax/initialmappingdb_unittest.php
=> 2016 04 05 import

application/controllers/fastlanecontroller.php, application/controllers/ngsimportcontroller.php, application/models/ngsimport.php, public/ajax/initialmappingdb.php, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngsfastlane_database_funcs.js, public/js/dolphin/ngsfastlane_funcs.js, public/js/dolphin/ngsget_funcs.js, public/js/dolphin/ngsstatus_funcs.js, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/pipeline_gen_funcs.js, public/js/dolphin/sessionget_funcs.js, public/js/dolphin/tablecreator_funcs.js, unitTesting/ajax/initialmappingdb_unittest.php
Reverts UMMS-Biocore/dolphin-ui#361
=> Revert "2016 04 05 import"

application/views/admindolphinstats/index.php, public/ajax/adminstatquerydb.php, public/js/dolphin/admin_dolphin_stats.js, public/js/dolphin/admin_galaxy_stats.js, unitTesting/ajax/adminstatquerydb_unittest.php
=> testing admin stat errors

application/controllers/fastlanecontroller.php, application/controllers/ngsimportcontroller.php, application/models/ngsimport.php, public/ajax/initialmappingdb.php, public/ajax/ngsquerydb.php, public/ajax/sessionrequests.php, public/js/dolphin/initialrun_funcs.js, public/js/dolphin/ngsfastlane_database_funcs.js, public/js/dolphin/ngsfastlane_funcs.js, public/js/dolphin/ngsget_funcs.js, public/js/dolphin/ngspost_funcs.js, public/js/dolphin/ngsstatus_funcs.js, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/pipeline_gen_funcs.js, public/js/dolphin/sessionget_funcs.js, public/js/dolphin/tablecreator_funcs.js, unitTesting/ajax/initialmappingdb_unittest.php, unitTesting/ajax/ngsquerydb_unittest.php
Don't push, I'm testing to make sure everything is here.
=> switched from previous branch, testing

public/api/funcs.php, scripts/dolphin_wrapper.py
Reverts UMMS-Biocore/dolphin-ui#377
=> Revert "Merge branch"

public/js/dolphin/reports_funcs.js
Reverts UMMS-Biocore/dolphin-ui#482
=> Revert "2016 07 13 summary"

public/api/getsamplevals.php, public/js/dolphin/ngstrack_stats.js, public/js/dolphin/tablecreator_funcs.js
stash whatever changes are on production to merge this.  this was a bug that sam brought to my attention
=> 2016 07 21 table

public/js/dolphin/pipeline_error_checks.js
rsem no genome bam + rseqc check
=> rsem error check

scripts/dolphin_wrapper.py
latest email update isn't sending emails upon error, need to revert back to old error update, with code.
=> error push

.travis.yml, config/config.ini, config/config.php, includes/login.php
Add removed credentials to salt file upon merge.
=> moved encode creds

application/views/stat/status.php, public/ajax/ngsalterdb.php, public/ajax/ngsquerydb.php, public/api/funcs.php, public/js/dolphin/ngsget_funcs.js, public/js/dolphin/ngspost_funcs.js
allows for users that are not the owner to reset, rerun, or resume
=> 2016 09 23 jobs

application/views/dolphinstats/index.php, public/ajax/statquerydb.php, public/js/dolphin/admin_dolphin_stats.js, public/js/dolphin/admin_galaxy_stats.js, public/js/dolphin/dolphin_stats.js, public/js/dolphin/galaxy_stats.js
This push will pass once 2016_11_16_reports is pushed
=> 2016 11 16 usertab

application/views/admindolphinstats/index.php, application/views/dolphinstats/index.php, public/ajax/adminstatquerydb.php, public/ajax/statquerydb.php, public/js/dolphin/dolphin_stats.js, unitTesting/ajax/adminstatquerydb_unittest.php, unitTesting/ajax/statquerydb_unittest.php
I want to make sure this works on dolphin dev before merging
=> 2016 11 17 tables

application/views/encode/index.php, db/2016_11_29_parentfile.sql, public/ajax/encode_files.php, public/ajax/encode_tables.php, public/js/dolphin/encode_funcs.js, public/js/dolphin/encode_html.js
Do not push/merge until final word is given
=> 2016 11 18 encode

public/ajax/encode_files.php, public/ajax/encode_patch.php, public/ajax/encode_post.php, public/js/dolphin/encode_funcs.js, public/js/dolphin/encode_html.js
=> 2017 01 11 encode

application/views/backuptracking/footer.php, application/views/stat/footer.php, application/views/stat/status.php, public/js/dolphin/backup_tracking.js, public/js/dolphin/ngstrackstatus.js
Reverts UMMS-Biocore/dolphin-ui#603
=> Revert "2017 02 26ngstrackstatus"
